# The following lines were added by Docker Desktop to add commands to your PATH.
export PATH="$PATH:/Users/zachary.gallagher/.docker/bin"
# End of Docker Desktop section.

eval "$(/opt/homebrew/bin/brew shellenv)"

# source ~/.zshrc

# Created by `pipx` on 2025-01-27 20:29:50
export PATH="$PATH:/Users/zachary.gallagher/.local/bin"
