## Alias config
alias k=kubectl
alias t=terraform
alias terrafrom=terraform

## Neovim
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
export GPG_TTY=$(tty)

## fzf
eval "$(fzf --bash)"

## BAT
export BAT_THEME=Dracula

## eza
alias ls="eza --color=always -snew --git"

## dracula dircolors (for BAT)
eval "$(dircolors ~/.dir_colors/dircolors)"

## zoxide
eval "$(zoxide init bash)"
alias cd="z"